### ISSUE TITLE
The measure of aspect ratio in ciou loss

### ISSUE THREAD

**Issue by John-Yao** [Zzh-tju/CIoU#12]
Hi,

I am curious about the aspect ratio term of ciou, why you use arctan and don't use w/h directly? 

Have you try w/h + l2 loss directly? Could you provide some details about it? 

Thanks!

**Comment by Zzh-tju** [comment]
w/h is unbounded, so arctan() makes it bounded in (0, π/2)

**Comment by John-Yao** [comment]
Thanks!

**Comment by 383156098** [comment]
> 

为什么不试用tanh? 或者其他的函数，arctan有什么特殊的吗？

**Comment by 383156098** [comment]
> w/h is unbounded, so arctan() makes it bounded in (0, π/2)

为什么试用arctan约束在0~π/2，用tanh或者其他函数约束到0~1可以吗？
