### ISSUE TITLE
No `distance` function

### ISSUE THREAD

**Issue by thuyngch** [Zzh-tju/CIoU#5]
Hi @Zzh-tju ,
Thanks for your great work of CIoU and Cluster NMS.

I noted that the Cluster NMS is so impressed. Without any modification in the model, by changing the last NMS, the mAP is improved significantly.
However, at https://github.com/Zzh-tju/CIoU/blob/master/layers/functions/detection.py#L3, the file https://github.com/Zzh-tju/CIoU/blob/master/layers/box_utils.py does not have **distance** function.
Could you help me to figure out that?

Thanks,

**Comment by Zzh-tju** [comment]
updated. closed.
